### ISSUE TITLE
Model files not found

### ISSUE THREAD

**Issue by jlaw9** [VGligorijevic/deepNF#1]
First of all, thanks for making this available! 
I tried running `python main.py example_params.txt` after downloading the annotations, but I get an error saying the models file `yeast_MDA_arch_2_final_res.h5` is not found (see below). If I change the `mark` parameter to `--all` it seems to run just fine.

Also, a little more description about what each parameter does (specifically `mark`) would definitely be helpful.

```
python main.py example_params.txt 
Using TensorFlow backend.
mark=--no
org=yeast
valid_type=th
model_type=mda
select_arch=[2]
ofile_keywords=final_res
epochs=10
batch_size=128
n_trials=10
K=3
alpha=0.98
models_path=models/
results_path=results/
###############################################################


### [1] Loading network...
### [2] Loading network...
### [3] Loading network...
### [4] Loading network...
### [5] Loading network...
### [6] Loading network...
### [Model] Running for architecture:  [12000, 600, 12000]
### Running for: yeast_MDA_arch_2_final_res.h5
Traceback (most recent call last):
  File "main.py", line 202, in <module>
    mid_model = load_model(models_path + model_name)
  File "/home/jeffl/git-workspace/from-lit/deepNF/venv/local/lib/python2.7/site-packages/keras/models.py", line 234, in load_model
    with h5py.File(filepath, mode='r') as f:
  File "/home/jeffl/git-workspace/from-lit/deepNF/venv/local/lib/python2.7/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/jeffl/git-workspace/from-lit/deepNF/venv/local/lib/python2.7/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = 'models/yeast_MDA_arch_2_final_res.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

**Comment by VGligorijevic** [comment]
Thanks for your interest in our method. deepNF works in two steps: 

first (if `mark=--all`) it creates keras models for selected architectures (`select_arch=[2]`) and saves them in `models_path=models/`. Then, it reads the models from `models_path=models/` and runs either cross-validation (if `valid_type=cv`) or temporal-holdout validation (if `valid_type=th`), and writes the performance results in `results_path=results/`. 

If `mark=--no` then it skips the first step, and only runs the validation step (of course, this works only if the models have been generated previously).

**Comment by VGligorijevic** [comment]
`main.py` is now modified to check for model existence first before running the validation step. Thanks a lot for pointing out this issue.

**Comment by bhoom10** [comment]
Hi 
I ran the command `python main.py` and got the same error again
I have attached the stack trace here - https://pastebin.com/EkJZVz3s 

What could be causing this issue to occur again? 
Can you please help me out?

Regards,
Bhoomika Agarwal

**Comment by jlaw9** [comment]
Looks like you're using the default value for `--models_path` of `./test_models`, but when trying to save the model there, that folder doesn't exist, thus giving the error. Creating that folder before running the code should fix your issue.
